# Generated by Django 5.2.8 on 2025-11-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microcurriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_superior', models.IntegerField(default=0)),
                ('nivel_normal', models.IntegerField(default=0)),
                ('nivel_bajo', models.IntegerField(default=0)),
                ('nivel_deficiente', models.IntegerField(default=0)),
                ('prerequisitos', models.TextField(blank=True, null=True)),
                ('departamento_oferente', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_asignatura', models.CharField(blank=True, max_length=50, null=True)),
                ('naturaleza_asignatura', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_asignatura', models.TextField(blank=True, null=True)),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('objetivos_especificos', models.TextField(blank=True, null=True)),
                ('competencias_genericas', models.TextField(blank=True, null=True)),
                ('estrategias_pedagogicas_metodologicas', models.TextField(blank=True, null=True)),
                ('referencias_bibliograficas', models.TextField(blank=True, null=True)),
                ('primer_parcial', models.IntegerField(default=0)),
                ('segundo_parcial', models.IntegerField(default=0)),
                ('tercer_parcial', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microcurriculos', to='academico.materia')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='microcurriculos', to='academico.programa')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCompetenciasEspecificas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_tematica', models.CharField(blank=True, max_length=150, null=True)),
                ('competencias_especificas', models.TextField(blank=True, null=True)),
                ('resultados_de_aprendizaje', models.TextField(blank=True, null=True)),
                ('nivel_superior', models.IntegerField(default=0)),
                ('nivel_normal', models.IntegerField(default=0)),
                ('nivel_bajo', models.IntegerField(default=0)),
                ('nivel_deficiente', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('microcurriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_competencias', to='microcurriculo.microcurriculo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMicrocurriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('tipo_asignatura', models.CharField(blank=True, max_length=50, null=True)),
                ('naturaleza_asignatura', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_lectivo', models.IntegerField(blank=True, null=True)),
                ('periodo_academico', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('total_horas', models.IntegerField(blank=True, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_micro', to='usuarios.docente')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_micro', to='academico.materia')),
                ('microcurriculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='microcurriculo.microcurriculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanMicrocurriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('tema', models.CharField(blank=True, max_length=200, null=True)),
                ('actividades', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='microcurriculo.planmicrocurriculo')),
            ],
            options={
                'ordering': ['semana'],
            },
        ),
    ]
