# Generated by Django 5.2.8 on 2025-11-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('asistencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademica',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_academicas', to='asistencia.aula'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_academicas', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='materiadocente',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias_docente', to='usuarios.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='materiadocente',
            unique_together={('docente', 'materia', 'rol')},
        ),
    ]
